######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 12 14:50:02 2011
######################################################################

TEMPLATE = app
TARGET = gpiotopower
DEPENDPATH += .
INCLUDEPATH += .

QT -= gui
include ( ../../prod.pri )
# install paths
target.path = $$VS_BIN_PATH
INSTALLS += target

extra.path = $$VS_CONF_PATH
INSTALLS += extra

INCLUDEPATH += ../../include

INCLUDEPATH += ../common
LIBS += -L../common -lcommon

INCLUDEPATH += ../../libs/qextserialport/src
LIBS += -L../../libs/qextserialport/src/build -lqextserialport

INCLUDEPATH += ../../libs/libVSCommon
LIBS += -L../../libs/libVSCommon -lVSCommon

# Input
HEADERS += \
        gpiotopower.h

SOURCES += \
        main.cpp \
        gpiotopower.cpp
