######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 12 14:50:02 2011
######################################################################

TEMPLATE = app
TARGET = powertogpio
DEPENDPATH += .
INCLUDEPATH += .

QT -= gui

# VitalSim2
include ( ../../../mkspecs/vitalsim2.pri )
include ( ../../prod.pri )
# install paths
target.path = $$VS_BIN_PATH
INSTALLS += target

extra.path = $$VS_CONF_PATH
INSTALLS += extra

INCLUDEPATH += ../common
LIBS += -L../common -lcommon

# qextserialport Library
QEXTSERIALPORT_BUILDDIR = ../../../libs/qextserialport
include( ../../../libs/qextserialport/qextserialport.pri )

# Input
HEADERS += \
        powertogpio.h

SOURCES += \
        main.cpp \
        powertogpio.cpp
